'use client';
import { useEffect, useState } from 'react';
import api from '@/lib/axios-client';

export default function AuthorApplicationManager() {
  const [applications, setApplications] = useState([]), [notice, setNotice] = useState('');
  const sortApplications = (items) => [...items].sort((a, b) => (a.status === 'PENDING' ? 0 : 1) - (b.status === 'PENDING' ? 0 : 1));
  useEffect(() => { const timer = window.setTimeout(() => { api.get('/author-applications').then((response) => setApplications(sortApplications(response.data.applications || []))).catch((error) => setNotice(error.response?.data?.message || 'โหลดคำขอไม่สำเร็จ')); }, 0); return () => window.clearTimeout(timer); }, []);
  const review = async (application, status) => { const rejectionReason = status === 'REJECTED' ? window.prompt('ระบุเหตุผลที่ปฏิเสธ') : ''; if (status === 'REJECTED' && !rejectionReason) return; try { const response = await api.patch('/author-applications', { userId: application.userId, status, rejectionReason }); setApplications((old) => old.map((item) => item.id === application.id ? response.data.application : item)); setNotice(response.data.message); } catch (error) { setNotice(error.response?.data?.message || 'ตรวจสอบคำขอไม่สำเร็จ'); } };
  const statusClass = { PENDING: 'bg-amber-100 text-amber-700', APPROVED: 'bg-emerald-100 text-emerald-700', REJECTED: 'bg-red-100 text-red-700' };
  const pendingCount = applications.filter((item) => item.status === 'PENDING').length;
  return <section className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">คำขอสมัครเป็นนักเขียน</h2><p className="text-sm text-slate-500">ตรวจสอบข้อมูลส่วนตัวและผลงานก่อนอนุมัติ Reader ให้เป็น Author</p></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-sm font-bold text-amber-700">รอตรวจสอบ {pendingCount} คำขอ</span></div>{notice && <p className="mb-4 rounded-xl bg-blue-50 p-3 text-sm text-[#3F6FAF]">{notice}</p>}{!applications.length ? <p className="rounded-xl border border-dashed p-5 text-slate-500">ยังไม่มีคำขอสมัครนักเขียน</p> : <div className="space-y-3">{applications.map((item) => <article key={item.id} className={`rounded-2xl border p-4 ${item.status === 'PENDING' ? 'border-amber-200 bg-amber-50/30' : ''}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{item.penName}</h3><p className="text-sm text-slate-500">{item.username} • {item.email}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClass[item.status]}`}>{item.status}</span></div><div className="mt-3 rounded-xl border border-blue-100 bg-blue-50/60 p-3 text-sm"><p className="font-bold text-[#203A5F]">ข้อมูลยืนยันตัวตน · สำหรับผู้ดูแลเท่านั้น</p><div className="mt-2 grid gap-1 text-slate-700 sm:grid-cols-2"><p><b>ชื่อจริง:</b> {item.fullName || '—'}</p><p><b>วันเกิด:</b> {item.birthDate || '—'}</p><p><b>โทร:</b> {item.phone || '—'}</p><p><b>ประเทศ:</b> {item.country || '—'}</p></div><p className="mt-2 text-xs text-slate-500">ยอมรับกฎเวอร์ชัน {item.rulesVersion || 'ข้อมูลเดิม'} {item.rulesAcceptedAt ? `เมื่อ ${new Date(item.rulesAcceptedAt).toLocaleString('th-TH')}` : ''}</p></div><p className="mt-3 text-sm text-slate-700">{item.introduction}</p><p className="mt-2 text-sm"><b>ประเภท:</b> {item.genres}</p>{item.sampleWork && <details className="mt-2 text-sm"><summary className="cursor-pointer font-semibold text-[#3F6FAF]">ดูตัวอย่างผลงาน</summary><p className="mt-2 whitespace-pre-wrap rounded-xl bg-slate-50 p-3">{item.sampleWork}</p></details>}{item.rejectionReason && <p className="mt-2 text-sm text-red-600">เหตุผล: {item.rejectionReason}</p>}{item.status === 'PENDING' && <div className="mt-4 flex gap-2"><button type="button" onClick={() => review(item, 'APPROVED')} className="rounded-lg bg-emerald-500 px-4 py-2 font-semibold text-white">อนุมัติเป็น Author</button><button type="button" onClick={() => review(item, 'REJECTED')} className="rounded-lg bg-red-500 px-4 py-2 font-semibold text-white">ปฏิเสธ</button></div>}</article>)}</div>}</section>;
}
